modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "${issues}"
license = "${license}"

[[mods]]
modId = "${modId}"
version = "${version}"
displayName = "${displayName}"
authors = "${authors}"
displayURL = "${homepage}"
description = '''
${description}
'''
logoFile = "${iconLogo}"

[[dependencies.drinkandstretch]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.drinkandstretch]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.drinkandstretch]]
modId = "cloth_config"
type = "required"
versionRange = "[15,16)"
ordering = "AFTER"
side = "CLIENT"

[[mixins]]
config = "drinkandstretch.mixins.json"
